lab_4_asp.net_mvc/TaskManager.MVC/ViewModels/TaskViewModel.cs
using System.Collections.Generic;
using System.Linq;
using TaskManager.DAL.Models;


namespace TaskManager.MVC.Models
{
    public class TaskModel
    {
        public IEnumerable<Task> Tasks { get; set; }
        // public int Id { get; set; }
        // public string Title { get; set; }
        // public string Description { get; set; }
        // public int Time { get; set; } 
        // public string Priority { get; set; }
        // public string Status { get; set; }
        // public string Project { get; set; }
        // public string Employee { get; set; }

    }

    public class OneTaskModel
    {
        public Task Task { get; set; }
    }
    // public static class TaskExtensions
    // {
    //     public static TaskModel FromContract(this BizzContracts.Task contract)
    //     {
    //         return new TaskModel
    //         {
    //             Id = contract.Id,
    //             Title = contract.Title,
    //             Description = contract.Description,
    //             Time = contract.Time,
    //             Priority = contract.Priority.Name,
    //             Status = contract.Status.Name,
    //             Project = contract.Project.Name,
    //             Employee = contract.Employee.FirstName+" "+contract.Employee.LastName
    //         };
    //     }
    //
    //     public static List<TaskModel> FromContract(this List<BizzContracts.Task> contracts)
    //     {
    //         return contracts.Select(x => x.FromContract()).ToList();
    //     }
    // }
}

lab_4_asp.net_mvc/TaskManager.MVC/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TaskManager.BLL.Services.Interfaces;
using TaskManager.MVC.Models;
using TaskManager.MVC.ViewModels;

namespace TaskManager.MVC.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ITaskService _taskService;
        private readonly IProjectService _projectService;
        private readonly IPriorityService _priorityService;
        private readonly IStatusService _statusService;
        private readonly ITeamService _teamService;
        private readonly IEmployeeService _employeeService;

        public EmployeeController(ILogger<HomeController> logger
            , ITaskService taskService
            , IProjectService projectService
            , IPriorityService priorityService
            , IStatusService statusService
            , ITeamService teamService
            , IEmployeeService employeeService
        )
        {
            _logger = logger;
            _taskService = taskService;
            _projectService = projectService;
            _priorityService = priorityService;
            _statusService = statusService;
            _teamService = teamService;
            _employeeService = employeeService;
        }
        // GET
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Employees()
        {
            var employees = _employeeService.GetEmployees();
            IEnumerable<EmployeeViewModel> employeesModels = new List<EmployeeViewModel>();
            foreach (var employee in employees)
            {
                employeesModels = employeesModels.Append(new EmployeeViewModel()
                {
                    Employee = employee,
                    CurrentTasks = _employeeService.GetEmployeeTasks(employee.Id).Count()
                });
            }
            return View(employeesModels);
        }
    }
}

lab_4_asp.net_mvc/TaskManager.MVC/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TaskManager.BLL.Services.Interfaces;
using TaskManager.MVC.Models;
using TaskManager.MVC.ViewModels;

namespace TaskManager.MVC.Controllers
{
    public class ProjectController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ITaskService _taskService;
        private readonly IProjectService _projectService;

        public ProjectController(ILogger<HomeController> logger
            , ITaskService taskService
            , IProjectService projectService
        )
        {
            _logger = logger;
            _taskService = taskService;
            _projectService = projectService;
        }
        // GET
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Projects()
        {
            var projects = new ProjectViewModel
            {
                Projects = _projectService.GetProjects()
            };
            return View(projects);
        }
    }
}

lab_4_asp.net_mvc/TaskManager.MVC/Controllers/TaskController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TaskManager.BLL.Services.Interfaces;
using TaskManager.DAL.Models;
using TaskManager.MVC.Models;
using TaskManager.MVC.ViewModels;

namespace TaskManager.MVC.Controllers
{
    public class TaskController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ITaskService _taskService;
        private readonly IProjectService _projectService;
        private readonly IPriorityService _priorityService;
        private readonly IStatusService _statusService;
        private readonly ITeamService _teamService;
        private readonly IEmployeeService _employeeService;

        public TaskController(ILogger<HomeController> logger
            , ITaskService taskService
            , IProjectService projectService
            , IPriorityService priorityService
            , IStatusService statusService
            , ITeamService teamService
            , IEmployeeService employeeService
        )
        {
            _logger = logger;
            _taskService = taskService;
            _projectService = projectService;
            _priorityService = priorityService;
            _statusService = statusService;
            _teamService = teamService;
            _employeeService = employeeService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Tasks()
        {
            var taskModel = new TaskModel()
            {
                Tasks = _taskService.GetTasks()
            };
            return View(taskModel);
        }

        public IActionResult TaskDetails(int id)
        {
            var task = new OneTaskModel
            {
                Task = _taskService.GetTask(id)
            };
            return View(task);
        }

        public IActionResult ProjectTasks(int id)
        {
            var tasks = new TaskModel
            {
                Tasks = _taskService.GetTasksOfProject(id)
            };
            return View(tasks);
        }
        public IActionResult EmployeeTasks(int id)
        {
            var tasks = new TaskModel
            {
                Tasks = _employeeService.GetEmployeeTasks(id)
            };
            return View(tasks);
        }
        public IActionResult UpdateTaskStatus(int id)
        {
            var task = new OneTaskModel
            {
                Task = _taskService.GetTask(id)
            };
            return View(task);
        }

        public IActionResult NewTask()
        {
            IEnumerable<OneProjectViewModel> projectModels = new List<OneProjectViewModel>();
            var projects = _projectService.GetProjects();
            foreach (var project in projects)
            {
                IEnumerable<Employee> employees = _teamService.GetTeamEmployeesOfProject(project.Id);
                IEnumerable<EmployeeViewModel> employeeModels = new List<EmployeeViewModel>();
                foreach (var employee in employees)
                {
                    employeeModels = employeeModels.Append(new EmployeeViewModel
                    {
                        Employee = employee,
                        CurrentTasks = _employeeService.GetEmployeeTasks(employee.Id).Count()
                    });
                }
                projectModels = projectModels.Append(new OneProjectViewModel
                {
                    Project = project,
                    EmployeeViewModels = employeeModels
                });
            }

            return View(projectModels); //todo: how to give project list and employee list??
        }

        

        [HttpPost]
        public IActionResult NewTask(string title, string description,
            int timeForAccomplishment, int priority, int project, int employee)
        {
            var task = new Task
            {
                Title = title,
                Description = description,
                Time = timeForAccomplishment,
                Priority = _priorityService.GetPriorityById(priority),
                Status = _statusService.GetStatusById(1),
                Project = _projectService.GetProject(project),
                Employee = _employeeService.GetEmployee(employee)
            };
            _taskService.AddNewTask(task);

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult PutTaskStatus(int taskId, int status)
        {
            var a = 0;

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

lab_4_asp.net_mvc/TaskManager.MVC/Views/Task/EmployeeTasks.cshtml
@model TaskModel

@{
    ViewData["Title"] = "Project Tasks Page";
}

<h1>All project tasks</h1>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Project</th>
            <th>Employee</th>
            <th>Status</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @{
            foreach (var task in Model.Tasks)
            {
                <tr>
                    <td>@task.Id</td>
                    <td>@task.Title</td>
                    <td>@task.Project.Name</td>
                    <td>@task.Employee.FirstName @task.Employee.LastName</td>
                    <td>@task.Status.Name</td>
                    <td>
                        <div class="btn-group-vertical">
                            <button class="btn btn-info" onclick="
                                        location.href='@Url.Action("TaskDetails", "Task", new {id = task.Id})'">Details</button>
                            <button class="btn btn-info" onclick="
                                        location.href='@Url.Action("UpdateTaskStatus", "Task", new {id = task.Id})'">Update Status</button>
                        </div>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

lab_4_asp.net_mvc/TaskManager.MVC/Views/Task/Index.cshtml
@{
    ViewData["Title"] = "Task Page";
}

<h1>Here will be displayed menu where can be selected option to display something</h1>
<div>

    <div class="btn-group-vertical">
        <button class="btn btn-info" onclick="
                                            location.href='@Url.Action("Tasks", "Task")'">Get All Tasks</button>
        <button class="btn btn-info" onclick="
                                        location.href='@Url.Action("Projects", "Project")'">Get Tasks By Projects</button>
        <button class="btn btn-info" onclick="
                                        location.href='@Url.Action("NewTask", "Task")'">Add New Task</button>
        <button class="btn btn-info" onclick="
                                                location.href='@Url.Action("Employees", "Employee")'">Get Employee Unfinished Tasks</button>
        <button class="btn btn-info" onclick="
                                            location.href='@Url.Action("UpdateTaskStatus", "Task")'">Update Task Status</button>
    </div>

</div>

lab_4_asp.net_mvc/TaskManager.MVC/Views/Task/NewTask.cshtml
@model IEnumerable<TaskManager.MVC.ViewModels.OneProjectViewModel> 


@using (Html.BeginForm("NewTask", "Task", FormMethod.Post))
{
    <div class="form-group">
        <label>Title</label>
        <input type="text" class="form-control" name="title" placeholder="Enter task title...">
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea class="form-control" name="description" rows="5" 
                placeholder="Enter task description..."></textarea>
    </div>
    <div class="form-group">
        <label>Time for accomplishment</label>
        <textarea class="form-control" name="timeForAccomplishment" rows="1" 
                placeholder="Enter time in hours..."></textarea>
    </div>
    <div class="form-group">
        <label>Priority</label>
        <select class="form-control" name="priority">
            <option value="1">Low</option>
            <option value="2">Medium</option>
            <option value="3">High</option>
        </select>
    </div>
    <div class="form-group">
        <label>Project</label>
        <select class="form-control" name="project">
            @{
                foreach (var project in Model)
                {
                    <option value=@project.Project.Id>@project.Project.Name</option>
                }
            }
        </select>
    </div>
    <div class="form-group">
        <label>Employee</label>
        <select class="form-control" name="employee">
            @{
                // int projectId = 
                foreach (var project in Model)
                {
                    foreach (var employee in project.EmployeeViewModels)
                    {
                        <option value=@employee.Employee.Id>@employee.Employee.FirstName @employee.Employee.LastName :
                            @project.Project.Name : Current tasks @employee.CurrentTasks</option>
                    }
                }
            }
        </select>
    </div>
    <div></div>
    <div style="text-align: end">
        <p></p>
        <input type="submit" name="NewTask" value="Create" class="btn btn-success">
    </div>
}

lab_4_asp.net_mvc/TaskManager.MVC/Views/Task/ProjectTasks.cshtml
@{
    ViewData["Title"] = "Project Tasks Page";
}

<h1>All project tasks</h1>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Project</th>
            <th>Employee</th>
            <th>Status</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @{
            foreach (var task in Model.Tasks)
            {
                <tr>
                    <td>@task.Id</td>
                    <td>@task.Title</td>
                    <td>@task.Project.Name</td>
                    <td>@task.Employee.FirstName @task.Employee.LastName</td>
                    <td>@task.Status.Name</td>
                    <td>
                        <div class="btn-group-vertical">
                            <button class="btn btn-info" onclick="
                                        location.href='@Url.Action("TaskDetails", "Task", new {id = task.Id})'">Details</button>
                        </div>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

lab_4_asp.net_mvc/TaskManager.MVC/Views/Task/TaskDetails.cshtml
@{
    ViewData["Title"] = "Task Details Page";
}

<h1>Task details:</h1>
<div>
    <p>Title: @Model.Task.Title</p>
    <p>Description:  @Model.Task.Description</p>
    <p>Time for accomplishment:  @Model.Task.Time hours</p>
    <p>Priority:  @Model.Task.Priority.Name</p>
    <p>Status:  @Model.Task.Status.Name</p>
    <p>Project:  @Model.Task.Project.Name</p>
    <p>Employee:  @Model.Task.Employee.FirstName @Model.Task.Employee.LastName</p>
</div>

lab_4_asp.net_mvc/TaskManager.MVC/Views/Task/Tasks.cshtml
@{
    ViewData["Title"] = "Task Page";
}


<h1>Here will be displayed tasks by projects</h1>


@if (false)
{
    <span>There are no tasks</span>
}
else
{
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Project</th>
                <th>Employee</th>
                <th>Status</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @{
                foreach (var task in Model.Tasks)
                {
                    <tr>
                        <td>@task.Id</td>
                        <td>@task.Title</td>
                        <td>@task.Project.Name</td>
                        <td>@task.Employee.FirstName @task.Employee.LastName</td>
                        <td>@task.Status.Name</td>
                        <td>
                            <div class="btn-group-vertical">
                                <button class="btn btn-info" onclick="
                                        location.href='@Url.Action("TaskDetails", "Task", new {task.Id})'">Details</button>
                            </div>
                        </td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
}

lab_4_asp.net_mvc/TaskManager.MVC/Views/Task/UpdateTaskStatus.cshtml
@using System.Reflection.Metadata
@model OneTaskModel

@{
    ViewData["Title"] = "Task Details Page";
}

@using (Html.BeginForm("PutTaskStatus", "Task", FormMethod.Post))
{
    <h1>Task details:</h1>
    <div>
        <p name="taskId" value=@Model.Task.Id>
        <p>Title: @Model.Task.Title</p>
        <p>Description: @Model.Task.Description</p>
        <p>Time for accomplishment: @Model.Task.Time hours</p>
        <p>Priority: @Model.Task.Priority.Name</p>
        <div class="form-group">
            <label>Priority</label>
            <select class="form-control" name="status">
                <option value="1">NotStarted</option>
                <option value="2">OnExecution</option>
                <option value="3">Done</option>
            </select>
        </div>
        <p>Project: @Model.Task.Project.Name</p>
        <p>Employee: @Model.Task.Employee.FirstName @Model.Task.Employee.LastName</p>
    </div>
    <div></div>
    <div style="text-align: end">
        <p></p>
        <input type="submit" name="NewTask" value="Update" class="btn btn-success">
    </div>
}